language: c
sudo: true
services:
- docker
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - valgrind
script:
- make
- valgrind --tool=cachegrind --log-file=empty.cachegrind.log --cachegrind-out-file=empty.cachegrind ./empty.prog
- make check

env:
  global:
    DEPLOY_HOST=55a1cc835004460171000096@builds.koszek.com
    DEPLOY_LOCATION=app-root/runtime/repo/
    DEPLOY_KEY=6bcc3ab8dd25
    DEPLOY_FILE=travis_deploy/valgrind_edu

after_success:
- make pack
- RELFILENAME=`make relfilename`
- git clone https://github.com/wkoszek/travis_deploy.git
- ./travis_deploy/deploy.sh ${RELFILENAME}
