language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - valgrind
script:
- make
- make check
deploy:
  provider: openshift
  user: wkoszek@gmail.com
  password:
    secure: IX6R7P/YN+U1M2Fh1saDULgz05nAXBtqOT4OuLc4GunD/8uMZQLL2s9k9xrXiObtpmxp1pvPedJH9VIXliO7TxtdD+TcWiNRReWLHTVgarokHP/E1huVnuvDAoc42jIw4a9SYV2ilV6/vNLXLktCGqXUD7NXGmTF0xC+MTGF1G2EL1UJvZ+yT+HWKZfGomIqrPquiFJ6l0CBZYnrue+cyd115i5c7p2nxGNIFMe6swVM8PrAK4sA7xuSEJK+hk/TpvrV50QHFfN84fm/mUEFAx2Vwf0lAdFtu4wpBrZgyxxUwIJcUKgJ+O7RdpKrQRpMhSSJMxo1sX8Tpp2qen36tLtkXTTVT2sNLIEK2dOgryF6wiykD7g/lfYlsd+VWMJJ/+PFhyE5tMTIy3ouTmCEuQxZh6pwu6AiUND7sqyTOoea3koGD3QwhpgNsHtbO+02moy6K0wvaKvO9tqcBMuQWQklhk8VJrmltDFNp1itPhwt5mN3oXard72NhKT7nRTMcz1Qx67221Dm612KNhViBeq3hXBEir1TjH0vi77V7W4wMnCukUVEme6wIvBQMfmLFYiqlqUDEhLDqajX7lLCZMEYF+lHj5+UbIRZWI42o/lOyr6uYlMz6URt3e19N2V5Kh+vz8CwDwHYSTc/17lG4WwFevSD0HMqQbt/7reFlLk=
  app: builds
  domain: builds-koszek.rhcloud.com
  skip_cleanup: true
