language: c
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - valgrind
script:
- make
- make check

env:
  global:
    DEPLOY_HOST=55a1cc835004460171000096@build.koszek.com
    DEPLOY_LOCATION=app-root/runtime/repo/
    DEPLOY_KEY=6bcc3ab8dd25
    DEPLOY_FILE=travis_deploy/valgrind_edu

after_success:
- make pack
- git clone https://github.com/wkoszek/travis_deploy.git
- ./travis_deploy/deploy.sh /tmp/valgrind_edu.tar.bz2
